config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  devise_for :users

  get '/home' => 'landing_page#home'

  devise_scope :user do
    get '/terms' => 'devise/registrations#terms'
  end

  root 'landing_page#home'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/job_approval.rb
class JobApproval < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :small => "200x200>", :thumb => "100x100>" },
                             :default_url => "/images/:style/profilepic.png",
                             :storage => :dropbox,
                             :dropbox_credentials => Rails.root.join("config/extras/dropbox.yml"),
                             :dropbox_options => {
                               :path => proc { |style| "#{id}/#{avatar.original_filename}" }
                             }


  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes
  validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_filter :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :name, :email, :password, :current_password) }

  end

  def after_sign_in_path_for(resource)
    jobs_path#set path to go after sign in
  end

end

app/controllers/job_approval_controller.rb
class JobApprovalController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.create_by = current_user.id # store curr user id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :duration, :budget, :description, :skill, :status, :create_by)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_approval_helper.rb
module JobApprovalHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" style="padding-top:50px;padding-bottom:50px;">
  <div>
    <div class="row" style="padding-top:5px;padding-bottom:5px;">
      <div class="field">
        <div class="col-md-2"><%= f.label :title %></div>
        <div class="col-md-6"><%= f.text_field :title, :class=>"form-control" %></div>
      </div>
    </div>
    <div class="row" style="padding-top:5px;padding-bottom:5px;">
      <div class="field">
        <div class="col-md-2"><%= f.label :duration %></div>
        <div class="col-md-6"><%= f.text_field :duration, :class=>"form-control" %></div>
      </div>
    </div>
    <div class="row" style="padding-top:5px;padding-bottom:5px;">
      <div class="field">
        <div class="col-md-2">  <%= f.label :budget %> </div>
        <div class="col-md-6"><%= f.text_field :budget, :class=>"form-control" %></div>
      </div>
    </div>
    <div class="row" style="padding-top:5px;padding-bottom:5px;">
      <div class="field">
        <div class="col-md-2"><%= f.label :description %></div>
        <div class="col-md-6"><%= f.text_area :description, cols:"100", rows:"15", :class=>"form-control" %></div>
      </div>
    </div>
    <!-- <div class="field">
      <%= f.label :skill %>
      <%= f.text_field :skill %>
    </div>
    <div class="field">
      <%= f.label :status %>
      <%= f.text_field :status %>
    </div>
    <div class="field">
      <%= f.label :create_by %>
      <%= f.number_field :create_by %>
    </div> -->
    <div class="row">
      <div class="col-md-8">
        <div class="actions text-right">
          <%= f.submit :class=>"btn btn-lg btn-action"%>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/jobs/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <header class="page-header">
      <h1 class="page-title">Editing Job</h1>
    </header>
    <%#= link_to 'Back to job listings', jobs_path, :class=>"btn btn-xs btn-action"  %>
    <%= link_to 'Back to previous page', @job, :class=>"btn btn-xs btn-action"  %>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
			<div class="row">
				<div class="col-lg-8">
        		<header class="page-header">
        			<h1 class="page-title">Job Listings</h1>
        		</header>
				</div>
				<div class="text-right col-lg-4">
					<br>
					<%= link_to "New Job", new_job_path, :class => "btn btn-action" %>
				</div>
			</div>
	</div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
		<table class="table table-striped">
			<tbody>
				<!-- <tr >
					<td><span class="label label-success">Part time</span></td>
					<td><strong><a href="view-job.html">Refrigeration Repair Technician</a></strong><br />
						<a href="#">Sears Corp</a> &ndash; Posted by <a href="#">appthemedemo</a>
					</td>
					<td>Austin<br />Texas, United States</td>
					<td> 23 Jan 2013</td>
				</tr> -->

        <% @jobs.each do |job| %>
          <tr class=''>
            <td><span class="label label-success">Status</span></td>
            <td><strong><%= link_to "#{job.title}", job  %></strong><br />
              <%= job.description %>
            </td>
            <td><%= number_to_currency(job.budget, :unit => "€") %> <br/> <%= job.duration %></td>
            <!-- <td> Posted by: <%= job.create_by %></td> -->
          </tr>
        <% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/jobs/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <%= link_to '← Back to all Jobs', jobs_path, :class => "btn btn-link" %>
  </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
      <header class="page-header">
        <h1 class="page title">New Job</h1>
      </header>
      <b> Please fill in job details in the form below. </b>
      <%= render 'form' %>

      <!-- <%= link_to 'Back', jobs_path, :class=>"btn btn-xs btn-action" %>
      <%= link_to 'Home', root_url, :class=>"btn btn-xs btn-action"%> -->
    </div>
</div>

app/views/jobs/show.html.erb
<div class="container" style="padding-top:50px;padding-bottom:50px;">
  <div class="col-md-8 col-md-offset-2">
      <div class="row">
        <p>
          <div class="col-md-2"><strong>Title</strong></div>
          <div class="col-md-8"><%= @job.title %></div>
        </p>
      </div>

      <div class="row">
        <p>
          <div class="col-md-2"><strong>Duration</strong></div>
          <div class="col-md-8"><%= @job.duration %></div>
        </p>
      </div>

      <div class="row">
        <p>
          <div class="col-md-2"><strong>Budget</strong></div>
          <div class="col-md-8"><%= number_to_currency(@job.budget, :unit => "€") %></div>
        </p>
      </div>

      <div class="row">
        <p>
          <div class="col-md-2"><strong>Description</strong></div>
          <div class="col-md-8"><%= @job.description %></div>
        </p>
      </div>
        <!-- <p>
          <div class="col-md-2"><strong>Skill</strong></div>
            <%#= @job.skill %>
        </p>

        <p>
          <div class="col-md-2"><strong>Status</strong></div>
            <%#= @job.status %>
        </p>

        <p>
          <div class="col-md-2"><strong>Create by</strong></div>
            <%#= @job.create_by %>
          <%# creator = User.all.find_by(:id =>@job.create_by) %>
          <%#= creator.name %>
        </p>
        -->
        <br>
      <div class="row">
        <% if current_user.id == @job.create_by %>
          <%= link_to 'Edit', edit_job_path(@job), :class => "btn btn-action" %>
        <% end %>
        <%= link_to 'Go to All Jobs', jobs_path, :class => "btn btn-action" %>
      </div>
  </div>
</div>

app/views/landing_page/home.html.erb
	<!-- Header -->
	<header id="head">
		<div class="container">
			<div class="row">
				<!-- <h1 class="lead">Jobby</h1> -->
				<!-- <p class="tagline">PENANG LARGEST PART TIME JOB PORTAL</p> -->
				<div class="center-block">
					<p class="tagline2 center-block">Penang Part Time Job Portal</p>
				</div>
				<p class="taglinebtn">
          <!-- <%= link_to "Find a Job", new_user_session_path, :class => 'btn btn-default btn-lg', :role => 'button' %> -->
          <%= link_to "Post a Job", new_user_session_path, :class => 'btn btn-action btn-lg', :role => 'button' %>
        </p>
			</div>
		</div>
	</header>
	<!-- /Header -->

	<!-- /Flash Message -->
	<div class="container">
		<div class="row">
				<%#= render 'layouts/flash_messages' %>
		</div>
	</div>

	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">The best place to look for the job you are passionate about</h2>
		<p class="text-muted">
      Choose a job you love, and you will never have to work a day in your life.<br>
		  - Confucius
		</p>
	</div>
	<!-- /Intro-->

	<!-- Highlights - jumbotron -->
	<div class="jumbotron top-space">
		<div class="container">

			<h3 class="text-center thin">It is all in Jobby</h3>

			<div class="row">
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-globe fa-5"></i>From A - Z</h4></div>
					<div class="h-body text-center">
						<p>New job opportunities are being offered at Jobby everyday. Here, you can always find a job you love.</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-flash fa-5"></i>Lightning Fast Execution</h4></div>
					<div class="h-body text-center">
						<p>Get your response quickly, whether you are hiring or looking for a job.</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-heart fa-5"></i>Passionate Talents</h4></div>
					<div class="h-body text-center">
						<p>From technicians to website builders, the experts are always in the best shape to serve.</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-users fa-5"></i>Strong Community</h4></div>
					<div class="h-body text-center">
						<p>Thousands of people actively engage with Jobby every month, new solutions being created for you everyday.</p>
					</div>
				</div>
			</div> <!-- /row  -->

		</div>
	</div>
	<!-- /Highlights -->

	<!-- container -->
	<div class="container">

		<h2 class="text-center top-space">Happy Recruiters and Job Finders</h2>
		<br>

		<div class="row">
			<div class="col-sm-6">
				<h3>Love the job I got from Jobby. I am happy to be part of the community. </h3>
				<p>- Sam Smith, Web Developer</p>
			</div>
			<div class="col-sm-6">
				<h3>Finding talents has never been so easy with Jobby.</h3>
				<p>- Calvin Harris, Creative Mind Recruitment Firm</p>
			</div>
		</div> <!-- /row -->

		<div class="row">
			<div class="col-sm-6">
				<h3>Jobby has a comprehensive list of jobs for you to choose from, I've never worried about
					my opportunity in Jobby.</h3>
				<p>- Nina Dobrev, Marketing Assistant</p>
			</div>
			<div class="col-sm-6">
				<h3>Jobby always has persons I desire. Definitely recommended.</h3>
				<p>- Aaron Neville, HR Manager, I DO Event Management Corporation</p>
			</div>
		</div> <!-- /row -->

		<!-- <div class="jumbotron top-space">
			<h4>Dicta, nostrum nemo soluta sapiente sit dolor quae voluptas quidem doloribus recusandae facere magni ullam suscipit sunt atque rerum eaque iusto facilis esse nam veniam incidunt officia perspiciatis at voluptatibus. Libero, aliquid illum possimus numquam fuga.</h4>
     		<p class="text-right"><a class="btn btn-primary btn-large">Learn more »</a></p>
    </div> -->

</div>	<!-- /container -->

	<!-- Social links. @TODO: replace by link/instructions in template -->
	<section id="social">
		<div class="container">
			<div class="wrapper clearfix">
				<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_linkedin_counter"></a>
				<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
				</div>
				<!-- AddThis Button END -->
			</div>
		</div>
	</section>
	<!-- /social links -->

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <!-- <div class="alert alert-success"><%= notice %></div> -->
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <!-- <div class="alert alert-danger"></div> -->

  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="top-space">

  <div class="footer1">
    <div class="container">
      <div class="row">

        <div class="col-md-6 widget">
          <h3 class="widget-title" id="contact">Contact</h3>
          <div class="widget-body">
            <p>+04 1234567<br>
              <a href="mailto:#">jobby.freelance@gmail.com</a><br>
              <br>
              The Coding Shop House<br>84, Lebuh Melayu, 10100 Georgetown, Penang.
            </p>
          </div>
        </div>

        <div class="col-md-6 widget">
          <h3 class="widget-title">Follow Us</h3>
          <div class="widget-body">
              <div class="fb-page" data-href="https://www.facebook.com/thecodingshophouse" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false">
                <div class="fb-xfbml-parse-ignore">
                  <blockquote cite="https://www.facebook.com/thecodingshophouse">
                    <a href="https://www.facebook.com/thecodingshophouse">The Coding Shophouse</a>
                  </blockquote>
                </div>
              </div>
            <!-- <p class="follow-me-icons">
              <!-- <a href="https://www.facebook.com/thecodingshophouse"><i class="fa fa-facebook fa-2"></i></a> -->
              <!-- <a href=""><i class="fa fa-twitter fa-2"></i></a>
              <a href=""><i class="fa fa-linkedin fa-2"></i></a>
              <a href=""><i class="fa fa-github fa-2"></i></a> -->
            <!-- </p> -->
          </div>
        </div>

        <div class="col-md-6 widget">
          <!-- <h3 class="widget-title">Text widget</h3> -->
          <div class="widget-body">
            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, dolores, quibusdam architecto voluptatem amet fugiat nesciunt placeat provident cumque accusamus itaque voluptate modi quidem dolore optio velit hic iusto vero praesentium repellat commodi ad id expedita cupiditate repellendus possimus unde?</p>
            <p>Eius consequatur nihil quibusdam! Laborum, rerum, quis, inventore ipsa autem repellat provident assumenda labore soluta minima alias temporibus facere distinctio quas adipisci nam sunt explicabo officia tenetur at ea quos doloribus dolorum voluptate reprehenderit architecto sint libero illo et hic.</p> -->
          </div>
        </div>

      </div> <!-- /row of widgets -->
    </div>
  </div>

  <div class="footer2">
    <div class="container">
      <div class="row">

        <div class="col-md-6 widget">
          <div class="widget-body">
            <p class="simplenav">
              <b><a href="/">Home</a></b> |
              <!-- <a href="#">About</a> | -->
              <!-- <a href="#">Contact Us</a> | -->

              <% if user_signed_in? %>
                <b><%= link_to "Logout", destroy_user_session_path, method: :delete  %></b>
              <% else %>
                <b><%= link_to "Sign Up", new_user_registration_path %></b> |
                <b><%= link_to "Log In", new_user_session_path  %></b>
              <% end %>

            </p>
          </div>
        </div>

        <div class="col-md-6 widget">
          <div class="widget-body">
            <p class="text-right">
              <b>Copyright &copy; 2015, CodingshopHouse</b>
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="/"><%= image_tag("logo.png", :alt => "Jobby") %></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li class="active">
						<%= link_to 'Home', '/'%>
						<!-- <a href="/">Home</a> -->
					</li>
					<li><%= link_to 'Job Listing', jobs_path%></li>
					<li>
						<%= link_to 'Contact Us', '#contact'%>
					<!-- <a href="#contact">Contact Us</a> -->
					</li>

          <% if user_signed_in? %>
            <!-- <li>Logged in as <strong><%= current_user.email %></strong></li> -->
            <li><%= link_to 'Create Job', new_job_path%></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path%></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path%></li>
            <li><%= link_to "Sign In", new_user_session_path%></li>
          <% end %>

				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
	<!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jobby | One Stop Freelance Job</title>
  <!-- Latest compiled and minified CSS -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"> -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="The best place to look for the job you are passionate about">
	<meta name="author"      content="Codingshop House">

	<link rel="shortcut icon" href=<%= asset_path('gt_favicon.png')%>>

	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <!-- <link rel="stylesheet" href="assets/bootstrap.min.css">
	<link rel="stylesheet" href="assets/font-awesome.min.css"> -->


	<!-- Custom styles for our template -->
	<!-- <link rel="stylesheet" href="assets/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="assets/main.css"> -->

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="assets/js/html5shiv.js"></script>
	<script src="assets/js/respond.min.js"></script>
	<![endif]-->
</head>
<body class="home">
    <div id="fb-root"></div>


    <%= render 'layouts/menu' %>

    <%# render 'layouts/flash_messages' %>
    <!-- <div class="container-fluid"> -->
      <%= yield %>
    <!-- </div> -->

    <%= render 'layouts/footer' %>

  <!-- Latest compiled and minified JavaScript -->
  <!-- // <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <!-- // <script src="assets/headroom.min.js"></script>
  // <script src="assets/jQuery.headroom.min.js"></script>
  // <script src="assets/template.js"></script> -->
</body>
</html>